plugins:
  - jekyll-feed
  - jekyll-seo-tag
theme: minima
permalink: pretty
markdown: kramdown
url: ""
defaults:
  - scope:
      path: _data/portfolio.yml
    values:
      layout: default
hero_image: /assets/uploads/bridal_party_kiss.jpg
title: Sosa Studios
data_dir: _data
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - netlify.toml
email: info@sosastudios.com
description: Bridal hair in Standish, Maine â€” Timeless artistry for the modern bride.
baseurl: ""
