backend:
  name: github
  repo: tylermhansen/SosaStylesSite
  branch: main

media_folder: assets/uploads
public_folder: /assets/uploads

collections:
  - name: portfolio
    label: Portfolio
    folder: _data
    create: false
    extension: yml
    format: yaml
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Alt Text", name: "alt", widget: "string" }
      - { label: "Image", name: "src", widget: "string" }
      - label: "Gallery"
        name: "images"
        widget: "list"
        field: { label: "Image", name: "image", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Package", name: "package", widget: "select", options: ["Classic", "Editorial"] }
      - { label: "Date", name: "date", widget: "string" }
